# Generated by Django 4.2.6 on 2023-10-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_rename_mname_categorydb_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='vidio',
            field=models.FileField(blank=True, null=True, upload_to='vidios'),
        ),
    ]
