# Generated by Django 4.2.6 on 2023-10-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_categorydb_vidio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='moviename',
            new_name='movie',
        ),
    ]
