# Generated by Django 4.2.6 on 2023-10-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_rename_moviename_categorydb_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='catname',
            new_name='category',
        ),
    ]
