# Generated by Django 4.2.6 on 2023-10-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_rename_catname_categorydb_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='addingcategorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(blank=True, max_length=40, null=True)),
                ('discription', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
