# Generated by Django 4.2.6 on 2023-10-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_addingcategorydb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addingcategorydb',
            old_name='movie',
            new_name='name',
        ),
    ]
