# Generated by Django 4.2.6 on 2023-10-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_rename_image_addingcategorydb_categoryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addingcategorydb',
            old_name='categoryimage',
            new_name='image',
        ),
    ]
