# Generated by Django 4.2.6 on 2023-10-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_rename_categoryimage_addingcategorydb_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='image',
            new_name='movieimage',
        ),
    ]
