# Generated by Django 4.2.6 on 2023-12-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_rename_image_categorydb_movieimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='topviewdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(blank=True, max_length=40, null=True)),
                ('director', models.CharField(blank=True, max_length=40, null=True)),
                ('discription', models.CharField(blank=True, max_length=40, null=True)),
                ('movieimage', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('vidio', models.FileField(blank=True, null=True, upload_to='vidios')),
            ],
        ),
    ]
