# Generated by Django 4.2.6 on 2023-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='signupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=30, null=True)),
                ('semail', models.CharField(blank=True, max_length=30, null=True)),
                ('susername', models.CharField(blank=True, max_length=30, null=True)),
                ('spassword', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
