# Generated by Django 4.2.6 on 2023-11-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='semail',
        ),
    ]
