# Generated by Django 4.2.6 on 2023-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0002_remove_signupdb_semail'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='mob',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
