# Generated by Django 4.2.6 on 2023-11-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0003_signupdb_img_signupdb_mob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupdb',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='signupdb',
            old_name='mob',
            new_name='smob',
        ),
    ]
