# Generated by Django 4.2.6 on 2023-11-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0004_rename_img_signupdb_image_rename_mob_signupdb_smob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='image',
        ),
    ]
