# Generated by Django 4.2.6 on 2023-11-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0005_remove_signupdb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdb',
            name='smob',
        ),
        migrations.AddField(
            model_name='signupdb',
            name='semail',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
