# Generated by Django 4.2.6 on 2023-11-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0007_contactdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='fulname',
            new_name='name',
        ),
    ]
