# Generated by Django 4.2.6 on 2023-11-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontview', '0008_rename_fulname_contactdb_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentdb',
            name='name',
        ),
    ]
